ALTER TABLE "User"
ADD COLUMN "drugLicence20B" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User"
ADD COLUMN "drugLicence21B" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User"
ALTER COLUMN "drugLicence20B" DROP DEFAULT;

ALTER TABLE "User"
ALTER COLUMN "drugLicence21B" DROP DEFAULT;