import type { Product, Order } from './types';

export const PRODUCTS: Product[] = [
  // { id: 'p1', name: 'Augmentin 625 Duo', company: 'GSK', composition: 'Amoxicillin 500mg + Clavulanic Acid 125mg', category: 'Tablets', pack: '10×10', mrp: 280, net: 198, expiry: 'Dec 2025' },
  // { id: 'p2', name: 'Dolo 650', company: 'Micro Labs', composition: 'Paracetamol 650mg', category: 'Tablets', pack: '15×10', mrp: 42, net: 30, expiry: 'Mar 2026' },
  // { id: 'p3', name: 'Pan 40', company: 'Alkem', composition: 'Pantoprazole 40mg', category: 'Tablets', pack: '10×10', mrp: 210, net: 148, expiry: 'Sep 2025' },
  // { id: 'p4', name: 'Azithral 500', company: 'Alembic', composition: 'Azithromycin 500mg', category: 'Tablets', pack: '3×10', mrp: 195, net: 138, expiry: 'Jun 2026' },
  // { id: 'p5', name: 'Benadryl Cough Syrup', company: 'J&J', composition: 'Diphenhydramine 14.08mg + Ammonium Chloride 138mg', category: 'Syrups', pack: '100ml', mrp: 115, net: 82, expiry: 'Jan 2026' },
  // { id: 'p6', name: 'Crocin Advance', company: 'GSK', composition: 'Paracetamol 500mg', category: 'Tablets', pack: '20×10', mrp: 52, net: 36, expiry: 'Nov 2025' },
  // { id: 'p7', name: 'Allegra 120', company: 'Sanofi', composition: 'Fexofenadine 120mg', category: 'Tablets', pack: '10×10', mrp: 320, net: 228, expiry: 'Aug 2026' },
  // { id: 'p8', name: 'Taxim-O 200', company: 'Alkem', composition: 'Cefixime 200mg', category: 'Tablets', pack: '5×10', mrp: 385, net: 272, expiry: 'May 2026' },
  // { id: 'p9', name: 'Montair LC', company: 'Sun Pharma', composition: 'Montelukast 10mg + Levocetirizine 5mg', category: 'Tablets', pack: '10×10', mrp: 298, net: 210, expiry: 'Feb 2026' },
  // { id: 'p10', name: 'Glycomet 500', company: 'USV', composition: 'Metformin 500mg', category: 'Tablets', pack: '20×10', mrp: 88, net: 62, expiry: 'Oct 2025' },
  // { id: 'p11', name: 'Deriphyllin Retard', company: 'Franco-Indian', composition: 'Theophylline 200mg + Etofylline 46mg', category: 'Tablets', pack: '10×10', mrp: 125, net: 88, expiry: 'Apr 2026' },
  // { id: 'p12', name: 'Lupihist Syrup', company: 'Lupin', composition: 'Chlorpheniramine 2mg + Dextromethorphan 10mg', category: 'Syrups', pack: '100ml', mrp: 72, net: 50, expiry: 'Jul 2026' },
  // { id: 'p13', name: 'Moxicip Eye Drops', company: 'Cipla', composition: 'Moxifloxacin 0.5%', category: 'Eye Drops', pack: '5ml', mrp: 145, net: 102, expiry: 'Mar 2027' },
  // { id: 'p14', name: 'Amoxil 500', company: 'GSK', composition: 'Amoxicillin 500mg', category: 'Tablets', pack: '10×10', mrp: 165, net: 116, expiry: 'Dec 2026' },
  // { id: 'p15', name: 'Cremaffin Plus', company: 'Abbott', composition: 'Sodium Picosulphate 7.5mg/5ml', category: 'Syrups', pack: '225ml', mrp: 195, net: 138, expiry: 'Jun 2025' },
  // { id: 'p16', name: 'Cyclopam', company: 'Indoco', composition: 'Dicyclomine 20mg + Paracetamol 500mg', category: 'Tablets', pack: '20×10', mrp: 140, net: 98, expiry: 'Sep 2026' },
  // { id: 'p17', name: 'Wysolone 10', company: 'Pfizer', composition: 'Prednisolone 10mg', category: 'Tablets', pack: '3×10', mrp: 52, net: 36, expiry: 'Jan 2027' },
  // { id: 'p18', name: 'Ganaton 50', company: 'Abbott', composition: 'Itopride 50mg', category: 'Tablets', pack: '10×10', mrp: 425, net: 298, expiry: 'Nov 2026' },
  // { id: 'p19', name: 'Ocuflox', company: 'Cipla', composition: 'Ofloxacin 0.3%', category: 'Eye Drops', pack: '5ml', mrp: 62, net: 44, expiry: 'Aug 2025' },
  // { id: 'p20', name: 'Volini Gel', company: 'Ranbaxy', composition: 'Diclofenac 1% + Methyl Salicylate 10%', category: 'Topical', pack: '30g', mrp: 185, net: 130, expiry: 'Apr 2027' },
];

export const COMPANIES = [...new Set(PRODUCTS.map(p => p.company))].sort();

export const MOCK_ORDERS: Order[] = [
  // {
  //   id: 'ORD-2024-001',
  //   retailerName: 'Rajesh Kumar',
  //   retailerShop: 'Kumar Medical Store',
  //   retailerPhone: '9876543210',
  //   retailerAddress: 'Shop 12, Gandhi Market, Padrauna, UP 274304',
  //   date: '2024-11-15',
  //   items: [
  //     { productId: 'p1', productName: 'Augmentin 625 Duo', quantity: 5, rate: 198 },
  //     { productId: 'p2', productName: 'Dolo 650', quantity: 10, rate: 30 },
  //   ],
  //   total: 1290,
  //   status: 'Delivered',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-002',
  //   retailerName: 'Sanjay Gupta',
  //   retailerShop: 'Gupta Pharmacy',
  //   retailerPhone: '9812345678',
  //   retailerAddress: 'Main Road, Kushinagar, UP 274403',
  //   date: '2024-11-18',
  //   items: [
  //     { productId: 'p7', productName: 'Allegra 120', quantity: 3, rate: 228 },
  //     { productId: 'p9', productName: 'Montair LC', quantity: 4, rate: 210 },
  //   ],
  //   total: 1524,
  //   status: 'Dispatched',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-003',
  //   retailerName: 'Meena Devi',
  //   retailerShop: 'New Life Medicals',
  //   retailerPhone: '9654321098',
  //   retailerAddress: 'Bus Stand Road, Deoria, UP 274001',
  //   date: '2024-11-20',
  //   items: [
  //     { productId: 'p8', productName: 'Taxim-O 200', quantity: 2, rate: 272 },
  //     { productId: 'p13', productName: 'Moxicip Eye Drops', quantity: 5, rate: 102 },
  //   ],
  //   total: 1054,
  //   status: 'Confirmed',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-004',
  //   retailerName: 'Prakash Singh',
  //   retailerShop: 'Singh Medical Agency',
  //   retailerPhone: '9723456789',
  //   retailerAddress: 'Civil Lines, Gorakhpur, UP 273001',
  //   date: '2024-11-22',
  //   items: [
  //     { productId: 'p3', productName: 'Pan 40', quantity: 8, rate: 148 },
  //     { productId: 'p6', productName: 'Crocin Advance', quantity: 5, rate: 36 },
  //   ],
  //   total: 1364,
  //   status: 'Submitted',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-005',
  //   retailerName: 'Asha Verma',
  //   retailerShop: 'Verma Drug House',
  //   retailerPhone: '9534567890',
  //   retailerAddress: 'Market Road, Basti, UP 272001',
  //   date: '2024-11-10',
  //   items: [
  //     { productId: 'p18', productName: 'Ganaton 50', quantity: 3, rate: 298 },
  //     { productId: 'p11', productName: 'Deriphyllin Retard', quantity: 6, rate: 88 },
  //   ],
  //   total: 1422,
  //   status: 'Delivered',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-006',
  //   retailerName: 'Vinod Tiwari',
  //   retailerShop: 'Tiwari Medical Store',
  //   retailerPhone: '9445678901',
  //   retailerAddress: 'Nehru Nagar, Azamgarh, UP 276001',
  //   date: '2024-11-08',
  //   items: [
  //     { productId: 'p5', productName: 'Benadryl Cough Syrup', quantity: 12, rate: 82 },
  //   ],
  //   total: 984,
  //   status: 'Cancelled',
  //   paymentMethod: 'COD',
  // },
  // {
  //   id: 'ORD-2024-007',
  //   retailerName: 'Dinesh Yadav',
  //   retailerShop: 'Yadav Medical Hall',
  //   retailerPhone: '9312345670',
  //   retailerAddress: 'Station Road, Mau, UP 275101',
  //   date: '2024-11-24',
  //   items: [
  //     { productId: 'p4', productName: 'Azithral 500', quantity: 4, rate: 138 },
  //     { productId: 'p16', productName: 'Cyclopam', quantity: 3, rate: 98 },
  //     { productId: 'p20', productName: 'Volini Gel', quantity: 6, rate: 130 },
  //   ],
  //   total: 1626,
  //   status: 'Packed',
  //   paymentMethod: 'COD',
  // },
];
